datadog:
  profiling:
    enabled: false
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com

  containerExclude: "kube_namespace:.*"
  containerInclude: "kube_namespace:member_ns1 "

  apm:
    portEnabled: true
    socketEnabled: true

  logs:
    enabled: true
    containerCollectAll: true

  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
          endpoint: "0.0.0.0:4317"
        http:
          enabled: true
          endpoint: "0.0.0.0:4318" 
